# action.yml
name: "Docker-Compose Publish"
author: "Booma"
description: "Publish all docker containers in docker-compose file"
branding:
  icon: "database"
  color: "red"
inputs:
  version:
    description: "version"
    required: false
  docker_compose:
    description: "docker-compose file to build and publish images from"
    required: true
  docker_user:
    description: "docker user"
    required: true
outputs:
  tag:
    description: "Tag that was published"
    value: ${{ steps.tag.outputs.semver }}
runs:
  using: "composite"
  steps:
    - id: tag
      run: |
        # if VERSION is not set, get it from git repo
        VERSION="${{ inputs.version }}"
        if [ -z "$VERSION" ]; then
            VERSION=$(${{ GITHUB_ACTION_PATH }}/src/get_version.sh)
        fi
        echo "VERSION: $VERSION"
        echo "::set-output name=semver::$(echo $VERSION)"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      shell: bash
    - id: publish
      run: ${{ GITHUB_ACTION_PATH }}/src/publish.sh ${{ inputs.version }} ${{ inputs.docker_compose }} ${{ inputs.docker_user }}
      shell: bash
